# Generated by Django 4.2.11 on 2026-02-13 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_storemanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraROIConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.IntegerField(default=1)),
                ("config_json", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField()),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "camera",
                    models.ForeignKey(
                        db_column="camera_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="roi_configs",
                        to="core.camera",
                    ),
                ),
            ],
            options={
                "db_table": "camera_roi_configs",
            },
        ),
        migrations.CreateModel(
            name="CameraHealth",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("fps", models.FloatField(blank=True, null=True)),
                ("lag_ms", models.IntegerField(blank=True, null=True)),
                ("reconnects", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField()),
                (
                    "camera",
                    models.ForeignKey(
                        db_column="camera_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="health",
                        to="core.camera",
                    ),
                ),
            ],
            options={
                "db_table": "camera_health",
            },
        ),
        migrations.CreateModel(
            name="CameraSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("snapshot_url", models.TextField(blank=True, null=True)),
                ("storage_key", models.TextField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                (
                    "camera",
                    models.ForeignKey(
                        db_column="camera_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="snapshots",
                        to="core.camera",
                    ),
                ),
            ],
            options={
                "db_table": "camera_snapshots",
            },
        ),
        migrations.AddConstraint(
            model_name="cameraroiconfig",
            constraint=models.UniqueConstraint(fields=("camera", "version"), name="uniq_camera_roi_version"),
        ),
        migrations.AddConstraint(
            model_name="camerahealth",
            constraint=models.UniqueConstraint(fields=("camera",), name="uniq_camera_health"),
        ),
    ]
