# Generated by Django 4.2.11 on 2026-02-13 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0001_camera_roi_health"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cameraroiconfig",
            old_name="config_json",
            new_name="payload",
        ),
        migrations.RemoveField(
            model_name="cameraroiconfig",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="cameraroiconfig",
            name="status",
            field=models.CharField(default="draft", max_length=20),
        ),
        migrations.AddField(
            model_name="cameraroiconfig",
            name="image_w",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cameraroiconfig",
            name="image_h",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cameraroiconfig",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="cameraroiconfig",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
