# Generated by Django 4.2.11 on 2026-01-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeEventReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=128, unique=True)),
                ('event_name', models.CharField(max_length=64)),
                ('source', models.CharField(default='edge', max_length=32)),
                ('store_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
