# Generated by Django 4.2.11 on 2026-02-01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("edge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EdgeToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("store_id", models.UUIDField(db_index=True)),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
