# Generated by Django 4.2.11 on 2026-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0007_vision_queue_state_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgeeventminutestats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
