# Generated by Django 4.2.11 on 2026-03-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0009_store_calibration_runs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storecalibrationrun',
            new_name='store_calib_store_i_e2dfd7_idx',
            old_name='store_calib_store_i_ef7f5f_idx',
        ),
    ]
