# Generated by Django 5.0.3 on 2026-03-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0011_edge_update_policy_event'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS edge_edgeeventreceipt;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='EdgeEventReceipt',
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name='edgeupdateevent',
            new_name='edge_update_store_i_1c0b1e_idx',
            old_name='edge_update__store_i_6b90ee_idx',
        ),
        migrations.RenameIndex(
            model_name='edgeupdateevent',
            new_name='edge_update_store_i_16185a_idx',
            old_name='edge_update__store_i_c3fb1c_idx',
        ),
        migrations.RenameIndex(
            model_name='edgeupdatepolicy',
            new_name='edge_update_store_i_267e3b_idx',
            old_name='edge_update__store_i_004a0d_idx',
        ),
    ]
