# Generated by Django 5.0.3 on 2026-03-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0012_delete_edgeeventreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeupdateevent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='edgeupdateevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('store_id', 'idempotency_key'), name='edge_update_event_store_idemp_uniq'),
        ),
    ]
