# Generated by Django 4.2.11 on 2026-02-01 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alertrule_auditlog_billingcustomer_camera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'owner'), ('admin', 'admin'), ('manager', 'manager'), ('viewer', 'viewer')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'store_managers',
                'managed': False,
            },
        ),
    ]
