# Generated by Django 4.2.11 on 2026-02-20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_organization_trial_ends_at"),
        ("core", "0003_storemanager"),
    ]

    operations = []

