# Generated by Django 5.0.3 on 2026-03-20 02:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pos_transaction_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_code', models.CharField(max_length=64)),
                ('recommended_action', models.TextField()),
                ('owner_role', models.CharField(default='store_manager', max_length=32)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('waiting_validation', 'waiting_validation'), ('validated', 'validated'), ('rejected', 'rejected'), ('closed', 'closed')], default='open', max_length=24)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], default='medium', max_length=16)),
                ('source', models.CharField(default='system', max_length=32)),
                ('assigned_to_user_uuid', models.UUIDField(blank=True, null=True)),
                ('created_by_user_uuid', models.UUIDField(blank=True, null=True)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(blank=True, db_column='camera_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calibration_actions', to='core.camera')),
                ('org', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calibration_actions', to='core.organization')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calibration_actions', to='core.store')),
            ],
            options={
                'db_table': 'calibration_actions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CalibrationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_before_url', models.TextField(blank=True, null=True)),
                ('snapshot_after_url', models.TextField(blank=True, null=True)),
                ('clip_before_url', models.TextField(blank=True, null=True)),
                ('clip_after_url', models.TextField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('captured_by_user_uuid', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.ForeignKey(db_column='action_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='core.calibrationaction')),
            ],
            options={
                'db_table': 'calibration_evidences',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CalibrationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=64)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('after_value', models.FloatField(blank=True, null=True)),
                ('delta_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('validated_by_user_uuid', models.UUIDField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.ForeignKey(db_column='action_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.calibrationaction')),
            ],
            options={
                'db_table': 'calibration_results',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='calibrationaction',
            index=models.Index(fields=['org', 'status'], name='cal_action_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationaction',
            index=models.Index(fields=['store', 'status'], name='cal_action_store_status_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationaction',
            index=models.Index(fields=['camera', 'status'], name='cal_action_camera_status_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationaction',
            index=models.Index(fields=['priority', 'created_at'], name='cal_action_prio_created_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationevidence',
            index=models.Index(fields=['action', 'captured_at'], name='cal_evidence_action_cap_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationresult',
            index=models.Index(fields=['action', 'metric_name'], name='cal_result_action_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationresult',
            index=models.Index(fields=['passed', 'validated_at'], name='cal_result_pass_valid_idx'),
        ),
    ]
