# Generated by Django 5.0.3 on 2026-03-12 22:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(db_index=True)),
                ('user_uuid', models.UUIDField(db_index=True)),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'copilot_conversations',
                'indexes': [models.Index(fields=['store_id', 'user_uuid', '-updated_at'], name='copilot_conv_store_user_idx'), models.Index(fields=['session_id'], name='copilot_conv_session_idx')],
            },
        ),
        migrations.CreateModel(
            name='CopilotDashboardContextSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(db_index=True)),
                ('account_state', models.CharField(default='unknown', max_length=32)),
                ('operational_state', models.CharField(default='not_started', max_length=32)),
                ('snapshot_json', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'copilot_dashboard_context_snapshots',
                'indexes': [models.Index(fields=['store_id', '-generated_at'], name='copilot_ctx_store_gen_idx'), models.Index(fields=['org_id', '-generated_at'], name='copilot_ctx_org_gen_idx')],
            },
        ),
        migrations.CreateModel(
            name='CopilotOperationalInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(db_index=True)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('critical', 'critical')], default='info', max_length=16)),
                ('headline', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('evidence_json', models.JSONField(default=dict)),
                ('actions_json', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'active'), ('archived', 'archived')], db_index=True, default='active', max_length=16)),
                ('source_window_start', models.DateTimeField(blank=True, null=True)),
                ('source_window_end', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'copilot_operational_insights',
                'indexes': [models.Index(fields=['store_id', 'status', '-created_at'], name='copilot_ins_store_st_ct_idx'), models.Index(fields=['org_id', 'status', '-created_at'], name='copilot_ins_org_st_ct_idx')],
            },
        ),
        migrations.CreateModel(
            name='CopilotReport72h',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ready', 'ready'), ('failed', 'failed')], db_index=True, default='pending', max_length=16)),
                ('summary_json', models.JSONField(default=dict)),
                ('sections_json', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_window_start', models.DateTimeField(blank=True, null=True)),
                ('source_window_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'copilot_reports_72h',
                'indexes': [models.Index(fields=['store_id', '-generated_at'], name='copilot_r72_store_gen_idx'), models.Index(fields=['org_id', '-generated_at'], name='copilot_r72_org_gen_idx')],
            },
        ),
        migrations.CreateModel(
            name='CopilotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'system'), ('assistant', 'assistant'), ('user', 'user')], default='user', max_length=16)),
                ('content', models.TextField()),
                ('metadata_json', models.JSONField(default=dict)),
                ('context_json', models.JSONField(default=dict)),
                ('citations_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='copilot.copilotconversation')),
            ],
            options={
                'db_table': 'copilot_messages',
                'indexes': [models.Index(fields=['conversation', '-created_at'], name='copilot_msg_conv_ct_idx')],
            },
        ),
    ]
