# Generated by Django 5.0.3 on 2026-03-14 03:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalWindowHourly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(db_index=True)),
                ('ts_bucket', models.DateTimeField(db_index=True)),
                ('window_minutes', models.PositiveSmallIntegerField(default=60)),
                ('metrics_json', models.JSONField(default=dict)),
                ('metric_status_json', models.JSONField(default=dict)),
                ('source_flags_json', models.JSONField(default=dict)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence_breakdown_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'operational_window_hourly',
                'indexes': [models.Index(fields=['store_id', '-ts_bucket'], name='op_window_store_bucket_idx'), models.Index(fields=['org_id', '-ts_bucket'], name='op_window_org_bucket_idx')],
                'unique_together': {('store_id', 'ts_bucket', 'window_minutes')},
            },
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(db_index=True, unique=True)),
                ('business_model', models.CharField(choices=[('default', 'default'), ('cafe', 'cafe'), ('gelateria', 'gelateria'), ('moda', 'moda'), ('lavanderia_self_service', 'lavanderia_self_service'), ('outro', 'outro')], default='default', max_length=64)),
                ('has_salao', models.BooleanField(default=False)),
                ('has_pos_integration', models.BooleanField(default=False)),
                ('opening_hours_json', models.JSONField(default=dict)),
                ('timezone_name', models.CharField(db_column='timezone', default='America/Sao_Paulo', max_length=64)),
                ('defaults_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'store_profile',
                'indexes': [models.Index(fields=['org_id', 'business_model'], name='store_profile_org_model_idx')],
            },
        ),
    ]
