# Generated by Django 5.0.3 on 2026-03-15 21:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0002_operationalwindowhourly_storeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(db_index=True)),
                ('action_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('insight_id', models.CharField(db_index=True, max_length=128)),
                ('action_type', models.CharField(default='whatsapp_delegation', max_length=64)),
                ('channel', models.CharField(default='whatsapp', max_length=32)),
                ('source', models.CharField(default='copilot_decision_center', max_length=64)),
                ('status', models.CharField(choices=[('dispatched', 'dispatched'), ('completed', 'completed'), ('failed', 'failed'), ('canceled', 'canceled')], db_index=True, default='dispatched', max_length=16)),
                ('baseline_json', models.JSONField(default=dict)),
                ('outcome_json', models.JSONField(default=dict)),
                ('impact_expected_brl', models.FloatField(default=0)),
                ('impact_realized_brl', models.FloatField(default=0)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('dispatched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'action_outcome',
                'indexes': [models.Index(fields=['store_id', '-dispatched_at'], name='action_outcome_store_ds_idx'), models.Index(fields=['org_id', '-dispatched_at'], name='action_outcome_org_ds_idx'), models.Index(fields=['store_id', 'status', '-dispatched_at'], name='action_outcome_store_st_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValueLedgerDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(db_index=True)),
                ('ledger_date', models.DateField(db_index=True)),
                ('value_recovered_brl', models.FloatField(default=0)),
                ('value_at_risk_brl', models.FloatField(default=0)),
                ('actions_dispatched', models.PositiveIntegerField(default=0)),
                ('actions_completed', models.PositiveIntegerField(default=0)),
                ('confidence_score_avg', models.FloatField(default=0)),
                ('method_version', models.CharField(default='value_ledger_v1_2026-03-15', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'value_ledger_daily',
                'indexes': [models.Index(fields=['store_id', '-ledger_date'], name='value_ledger_store_dt_idx'), models.Index(fields=['org_id', '-ledger_date'], name='value_ledger_org_dt_idx')],
                'unique_together': {('store_id', 'ledger_date')},
            },
        ),
    ]
